import {OpenAI} from "openai";

const openai = new OpenAI({
        apiKey: process.env.OPENAI_API_KEY,
    });

/**
 *
 * @param question
 * @param context
 */
export async function generateAnswer(
    question: string,
    context: string
): Promise<string>{

    //uses "as const" to tell TypeScript that role is specifically the literal value in the "",
    // instead of treating it as a generic string.
    const messages = [
        {
            role: "system" as const,
            content:
            "You are a study assistant. Answer the student's question using only the provided context. If the context" +
                "does not contain sufficient information to answer the question, say so, do not guess."
        },
        {
            role: "user" as const,
            content:
            `Context:
            ${context}
            
            Question:
            ${question}`
        },
    ];

    //send request to OpenAI
    const response = await openai.chat.completions.create({
        model: "gpt-4.1-mini",
        messages: messages,
    });

    //return the answer generated by AI that is stored in response
    const answer = response.choices[0].message.content;

    //return answer generated or return given string if answer was null
    return answer ?? "I could not generate an answer.";
}